version: '3'
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: example
  node:
    build: .
    depends_on:
      - db
    ports:
     - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: db